In [1]:
import numpy as np

# Data Types

##### Instruction: Run code, observe output and answer the questions

In [2]:
f = np.float64(1)
s = np.str_(1)
(f, s)

(np.float64(1.0), np.str_('1'))

In [3]:
f.dtype

dtype('float64')

In [4]:
s.dtype.name

'str32'

Question: What do type and type.name give ?

Answer: # Type your answer here

# Data Type Conversion

##### Instruction: Run code, observe output and answer the questions

In [5]:
f16 = np.float16(0.1)
f32 = np.float32(f16)
f64 = np.float64(f32)
(f16, f32, f64)

(np.float16(0.1), np.float32(0.099975586), np.float64(0.0999755859375))

In [6]:
newf = f64.astype(np.float16)
newf.dtype

dtype('float16')

Question: What can you tell about the differences between data types numpy.float16, numpy.float32 and numpy.float64?

Answer: # Type your answer here

Question: What does astype do?

Answer: # Type your answer here

# Array Creation and Array Dimension

##### Instruction: Run code, observe output and answer the questions

In [7]:
a1 = np.array([1,3,4,5])
a1

array([1, 3, 4, 5])

In [8]:
a2 = np.array([1,3,4,5], dtype=np.str_)
a2

array(['1', '3', '4', '5'], dtype='<U1')

In [9]:
a3 = np.array([1,3,4,5], dtype=np.complex128)
a3

array([1.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

Question: What is the difference between a1, a2, and a3?

Answer: # Type your answer here

In [10]:
b = np.array([[2,3,4,5],[6,7,8,9]], dtype=float)
b

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [11]:
c = np.array([[[3.8,4,5,6],[7,8,9,10]],[[11,12,13,14],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]], dtype=np.int_)

Question: What is the dimension of b? Indicate number of rows and number of columns.

Answer:  # Type your answer here

Question: What is the dimension of c ? Indicate number of sheets, number of rows and number of columns.

Answer: # Type your answer here

Question: What is the function to find dimension of numpy array ?

Answer: # Type your answer here

In [12]:
a = np.array([1,3,4,5])
b = np.array([[2,3,4,5],[6,7,8,9]], dtype=float)
c = np.array([[[3.8,4,5,6],[7,8,9,10]],[[11,12,13,14],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]], dtype=np.int_)

print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(3, 2, 4)


In [13]:
a = np.array([1,3,4,5])
b = np.array([[2,3,4,5],[6,7,8,9]], dtype=float)
c = np.array([[[3.8,4,5,6],[7,8,9,10]],[[11,12,13,14],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]], dtype=np.int_)

print(len(a))
print(len(b))
print(len(c))


4
2
3


In [14]:
a = np.array([1,3,4,5])
b = np.array([[2,3,4,5],[6,7,8,9]], dtype=float)
c = np.array([[[3.8,4,5,6],[7,8,9,10]],[[11,12,13,14],[15,16,17,18]],[[21,22,23,24],[25,26,27,28]]], dtype=np.int_)

print(a.size)
print(b.size)
print(c.size)


4
8
24


Question: What are differences between shape, size, and len()?

Answer: # Type your answer here

<caption><u><b>Exercise 0</u></b>: <br></caption>

Question: If we want to find out data type of of c, fill out the code below and run to check the output of your code is expected or not.

In [15]:
# Fill in the code for Exercise 0 here


# Array Access and Special Arrays

##### Instruction: If we would like to construct an array as shown in the shown images, what to fill for the code to construct such array?  
##### Note that you may need more than one line of code to construct the array.  Also, beware of data type.

<caption><u><b>Exercise 1</u></b>: Expect an output as shown in the image here: <br></caption>

Click this link to see image of expeced output: https://drive.google.com/file/d/1bgBMGc8ujVg__O177l5S9GookiXjDELh/view?usp=drive_link

In [16]:
# Fill in the code to receive the expected output from Exercise 1


<caption><u><b>Exercise 2</u></b>: Expect an output  as shown in the image here: <br></caption>
    
Click this link to see image of expeced output: https://drive.google.com/file/d/1WiwhuBBjO34qbRC4ROBYsJoK9jS9_Sz6/view?usp=sharing

In [17]:
# Fill in the code to receive the expected output from Exercise 2


# Array Slicing

##### Instruction: If we would like to use Numpy array slicing to construct a Numpy array as shown in the output, what to fill for the code?  

<caption><u><b>Exercise 3</u></b>: Expected output <br></caption>

[4. 5. 6.]

In [18]:
x = np.array([2,3,4,5,6,7,8,9], dtype=float)
# Fill in the code to receive the expected output from Exercise 3


<caption><u><b>Exercise 4</u></b>:  Expected output <br></caption

[6. 9.]

In [19]:
x = np.array([2,3,4,5,6,7,8,9], dtype=float)
# Fill the code to receive the expected output from Exercise 4


<caption><u><b>Exercise 5</u></b>: Expected output <br></caption>

[28 27 26 25 24 23 22 21]

In [20]:
y = np.array([[11,12,13,14,15,16,17,18],[21,22,23,24,25,26,27,28],[31,32,33,34,35,36,37,38]], dtype=np.int_)
# Fill the code to receive the expected output from Exercise 5



<caption><u><b>Exercise 6</u></b>: Expected output <br></caption>

[[24 26]

 [34 36]]


In [21]:
y = np.array([[11,12,13,14,15,16,17,18],[21,22,23,24,25,26,27,28],[31,32,33,34,35,36,37,38]], dtype=np.int_)
# Fill the code to receive the expected output from Exercise 6


# Array Comparison and Boolean Indexing

##### Instruction: Run code, observe output and answer the questions

<caption><u><b>Exercise 7</u></b>: <br></caption>

In [22]:
# Exercise 7
x = np.array([10,20,30])
y = np.array([1,20,3])
print(x == y)
print(x > y)

[False  True False]
[ True False  True]


Question: Explain why the result of Exercise 7 turns out like that

Answer: # Type your answer here

<caption><u><b>Exercise 8</u></b>: <br></caption>

In [23]:
# Exercise 8
x = np.array([10,20,30])
x[x < 15]

array([10])

Question: Explain why the result of Exercise 8 turns out like that

Answer: # Type your answer here

<caption><u><b>Exercise 9</u></b>: <br></caption>

In [24]:
# Exercise 9
y = np.array([1,20,3])
y[y < 15]

array([1, 3])

Question: Explain why the result of Exercise 9 turns out like that

Answer: # Type your answer here

# Array Assignment, View, and Copy

##### Instruction: Run code, observe output and answer the questions

In [25]:
x = np.array([10,20,30])
y1 = x
y1[2] = 0
x

array([10, 20,  0])

In [26]:
x = np.array([10,20,30])
y2 = x.view()
y2[2] = 0
x

array([10, 20,  0])

In [27]:
x = np.array([10,20,30])
y3 = x.copy()
y3[2] = 0
x

array([10, 20, 30])

Question:  From Assignment (=), View and Copy, which one duplicates the existing array by creating a new copy of the existing array?

Answer: # Type your answer here

# Array with equally-spaced values

Question: If we would like to create a new Numpy array with equally-spaced values as shown in the output, what to fill for the code?  

<caption><u><b>Exercise 10</u></b>: Expected Output<br></caption>

Click this link to see image of expeced output: <url>https://drive.google.com/file/d/12hhpoK6ElpbRpjBRSU-XuM670eBtB3ua/view?usp=drive_link</url>

In [28]:
# Fill the code to receive the expected output from Exercise 10
# You must use arange function to derive the Exercise-10 expected output


<caption><u><b>Exercise 11</u></b>: Expected Output<br></caption>
    
Click this link to see image of expeced output: https://drive.google.com/file/d/1K9Hd9Y4VeiEfUuBNutU19_6CbW2igi1g/view?usp=drive_link

In [29]:
# Fill the code to receive the expected output from Exercise 11
# You must use linspace function to derive the Exercise-11 expected output


# Array with randomized values

<caption><u><b>Exercise 12</u></b>: <br></caption>

Question: Create a Numpy array with 20 randomized values between 50 and 100.  Fill in and run your code below.

In [30]:
# Fill in the code for Exercise 12


<caption><u><b>Exercise 13</u></b>: <br></caption>

In [31]:
# Code for Exercise 13
x1 = np.random.random(10)
x1

array([0.27162758, 0.31949803, 0.56943041, 0.10547954, 0.8100055 ,
       0.98009436, 0.88988442, 0.40375853, 0.93919131, 0.06049698])

Question: Run code for Exercise 13 twice.  Insert the resulting arrays into output13.1 and output13.2 respectively.   

Answer: # Insert output13.1 from Exercise 13 here

Answer: # Insert output13.2 from Exercise 13 here

<caption><u><b>Exercise 14</u></b>: <br></caption>

In [32]:
# Code for Exercise 14
np.random.seed(0)
x2 = np.random.random(10)
x2

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

Question: Run code for Exercise 14 twice.  Insert the resulting arrays into output14.1 and output14.2 respectively.  

Answer: # Insert output14.1 from Exercise 14 here

Answer: # Insert output14.2 from Exercise 14 here

<caption><u><b>Exercise 15</u></b>: <br></caption>

In [33]:
# Code for Exercise 15
np.random.seed(5)
x3 = np.random.random(10)
x3

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

Question: Run code for Exercise 15 twice.  Insert the resulting arrays into output15.1 and output15.2 respectively.  

Answer: # Insert output15.1 from Exercise 15 here

Answer: # Insert output15.2 from Exercise 15 here

Question: How can you conclude from using np.random.seed and not using np.random.seed?

Answer: # Type your answer here

<caption><u><b>Exercise 16</u></b>: <br></caption>

Question: Create a Numpy array, named w, with 1000 randomized values based on normal distribution where mean = 0 and standard deviation = 1.   

**See whether the histogram of w looks like normal distribution where mean = 0 and standard deviation = 1 or not.**

**Help**: Click here for function to create a specific distribution and its parameters:
https://numpy.org/devdocs/reference/random/legacy.html#distributions

In [34]:
#Fill in your code for Exercise 16 to create numpy array as specified and named this array w.
#Fil in the code here

# Do not delete the following 2 lines.  It is given for plotting histogram using w.
import matplotlib.pyplot as plt
plt.hist(w, density=True)
plt.show()

NameError: name 'w' is not defined

<caption><u><b>Exercise 17</u></b>: <br></caption>

Question: Create a Numpy array, named w, with 1000 randomized values based on binomial distribution where n = 20 and p = 0.4.  

**See whether the histogram of w looks like binormial distribution where n = 20 and p = 0.2 or not.**

**Help**: Click here for function to create a specific distribution and its parameters:
https://numpy.org/devdocs/reference/random/legacy.html#distributions

In [35]:
#Fill in your code to create numpy array as specified and named this array w.
#Fil in the code here


# Do not delete the following 2 lines.  It is given for plotting histogram using w.
import matplotlib.pyplot as plt
plt.hist(w, density=True)

NameError: name 'w' is not defined

# Math Operations and Functions

In [36]:
# Run the following code and try to understand the outputs
x = np.array([10,20,30])
y = np.array([1,2,3])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))

[11 22 33]
[11 22 33]
[ 9 18 27]
[ 9 18 27]
[10 40 90]
[10 40 90]
[10. 10. 10.]
[10. 10. 10.]


In [37]:
# Run the following code and answer the question below
x = np.array([1,25,30])
print(x.sum())
print(x.cumsum())


56
[ 1 26 56]


Question: What is the difference between sum() and cumsum() functions?

Answer: # Type your answer here.

In [38]:
# Run the following code and try to understand the outputs
x = np.array([1,25,30])
print(np.sqrt(x))
print(np.log(x))
print(np.sin(x))

[1.         5.         5.47722558]
[0.         3.21887582 3.40119738]
[ 0.84147098 -0.13235175 -0.98803162]


<caption><u><b>Exercise 18</u></b>: <br></caption>

In [39]:
# Exercise 18

# Run the following code and answer the question below
w = np.random.normal(0,1,size=1000)
print(np.mean(w))
print(np.std(w))
print(np.min(w))
print(np.max(w))

0.03329544956095606
0.9894161308868268
-3.283915447626658
3.612318512197111


Question: Are the values from np.mean(w) and np.std(w) from Exercise 18 close to expected value and standard deviation of Normal(0,1)?


Answer: # Type your answer here

# Matrix Operations and Functions

In [40]:
# Run the following code and try to understand the outputs
x = np.array([10,20,30])
y = np.array([1,2,3])
x.dot(y)

np.int64(140)

In [41]:
# Run the following code and try to understand the outputs
A1 = np.array([[1,2], [3,4]])
A1.T

array([[1, 3],
       [2, 4]])

<caption><u><b>Exercise 19</u></b>: <br></caption>

In [42]:
# Exercise 19
A1 = np.array([[1,2], [3,4]])
B1 = np.array([[5,6], [7,8]])
print(A1+B1)
print(A1*B1)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


<caption><u><b>Exercise 20</u></b>: <br></caption>

In [43]:
# Exercise 20
A2 = np.matrix([[1,2], [3,4]])
B2 = np.matrix([[5,6], [7,8]])
print(A2+B2)
print(A2*B2)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


Question: From Exercises 19-20. what can you conclude from numpy array operation, compared to numpy matrix operation?

Answer : # Type your answer here